import React from 'react';

export const metadata = {
    title: 'How We Make Money | UKFreeComps',
    description: 'A transparent guide to how UKFreeComps is funded through affiliate marketing and advertising, complying with ASA guidelines.',
};

export default function HowWeMakeMoneyPage() {
    return (
        <div className="max-w-3xl mx-auto px-4 py-16 bg-white my-8 rounded-xl shadow-sm border border-slate-100">
            <h1 className="text-3xl font-bold text-slate-900 mb-8">How We Make Money</h1>

            <div className="bg-blue-50 border-l-4 border-monzo-blue p-4 mb-8 rounded-r-lg">
                <p className="text-sm font-bold text-blue-900 mb-1">Our Promise of Transparency</p>
                <p className="text-sm text-blue-800">
                    In accordance with the UK Advertising Standards Authority (ASA) guidelines, we believe in being completely transparent about how our site is funded. UKFreeComps will always remain 100% free for users.
                </p>
            </div>

            <div className="prose prose-sm prose-slate max-w-none space-y-6">
                <section>
                    <h2 className="text-xl font-bold text-slate-800">1. Affiliate Marketing</h2>
                    <p>
                        Our primary source of revenue is through affiliate marketing. When you click on certain "Enter Competition" links on our website and are redirected to a third-party promoter, we may earn a small commission or referral fee.
                    </p>
                    <p>
                        This tracking is done seamlessly via server-side redirects and standard affiliate cookies. It does not cost you anything, nor does it affect your chances of winning the competition.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-bold text-slate-800">2. Display Advertising</h2>
                    <p>
                        You may see display ads (such as banner ads) on UKFreeComps. We partner with advertising networks to serve these ads, which help cover our server and AI scraping costs. We strive to keep ads unobtrusive so they don't impact your browsing experience.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-bold text-slate-800">3. Editorial Independence</h2>
                    <p>
                        Our "Hype Score" and competition rankings are generated by AI analysis. <strong>We do not alter these scores or rankings based on affiliate partnerships.</strong> We list competitions regardless of whether they pay us a commission, ensuring you always get a comprehensive view of the best free UK competitions.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-bold text-slate-800">Contact Us</h2>
                    <p>
                        If you have any questions about our funding model or suspect a competition violates our terms, please get in touch.
                    </p>
                </section>
            </div>
        </div>
    );
}
